desc "Prepare widget to be deployed"
task "prepare" do
  system "rm -rf ../Airbrake.wdgt" if File.directory?("../Airbrake.wdgt")
  system "cp -R ../Airbrake ../Airbrake.wdgt"
  system "cp -R ../Airbrake.wdgt /tmp/"
end

desc "Create a new package"
task "deploy" => :prepare do
  path = "/tmp/Airbrake.wdgt/Airbrake.js"
  contents = File.read(path)
  contents.gsub!(/var DEBUG\s*=(.*?)$/sim, "var DEBUG = false;")

  File.open(path, "w+") << contents
end

desc "Install the widget"
task "install" => :prepare do
  system "open /tmp/Airbrake.wdgt"
  system "killall DashboardClient"
end